name: Example setup with docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Container
      run: docker build -t test:latest .github

    - name: Start Container
      run: docker run --privileged -v $(pwd):/gh-actions test:latest
